@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Jackson Moura",
  "email": "jackson@email.com",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "jackson@email.com",
  "password": "123456"
}

###

# @name create-question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Nova pergunta",
  "content": "Conteúdo da nova pergunta"
}

###

# @name test-route
DELETE {{baseUrl}}/answers/comments/71c1e458-766a-4ce6-b8fb-132b18ef82ff
Content-Type: application/json
Authorization: Bearer {{authToken}}
